version: '3'
services:
  postgres:
    image: postgres:9.6
    volumes:
      - pinarlabs_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=pinarlabs-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pinarlabs
    expose:
      - "5444"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8083:80"
    volumes:
      - ./pgadmin4-servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pinarlabs
      - PGADMIN_DEFAULT_EMAIL=db@pinarlabs.com
    links:
      - postgres
    logging:
      driver: none
volumes:
  pinarlabs_data:
  pgadmin_data:
